spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
server:
  port: 8080